### ISSUE TITLE
'pip install..' throws errors

### ISSUE THREAD

**Issue by marzaidi** [EliHei2/segger_dev#29]
OS: Linux, using CPU
python version: 3.10.15

i tried to install segger using both the conda installation and github installation. for conda installation, this is the error i get:

```
> pip install .                                                            
ERROR: Directory '.' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.
```

```
> pip install -e .                                               
Obtaining file:///dss/dsshome1/0C/go76saz2                                                                  
ERROR: file:///dss/dsshome1/0C/go76saz2 does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.
```  

```
> pip install "segger[cuda12,rapids12,cupy12,faiss]"                       
ERROR: Could not find a version that satisfies the requirement segger[cuda12,cupy12,faiss,rapids12] (from versions: none)
```

and this is the error i get for github installation after the same command: 

```
/segger_dev> pip install .

Processing /dss/dsshome1/0C/go76saz2/segger_dev
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [48 lines of output]
      configuration error: `project.optional-dependencies.rapids11[1]` must be pep508
      DESCRIPTION:
          Project dependency specification according to PEP 508
      
      GIVEN VALUE:
          "cuvs-cu11>=24.4.*"
      
      OFFENDING RULE: 'format'
      
      DEFINITION:
          {
              "$id": "#/definitions/dependency",
              "title": "Dependency",
              "type": "string",
              "format": "pep508"
          }
      
      For more details about `format` see
      https://validate-pyproject.readthedocs.io/en/latest/api/validate_pyproject.formats.html
      
      Traceback (most recent call last):
        File "/dss/dsshome1/0C/go76saz2/miniconda3/envs/segger-env/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/dss/dsshome1/0C/go76saz2/miniconda3/envs/segger-env/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/dss/dsshome1/0C/go76saz2/miniconda3/envs/segger-env/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/gpfs/scratch/pn57fo/go76saz2/go76saz2/pip-build-env-yzlgivyr/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 332, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
        File "/gpfs/scratch/pn57fo/go76saz2/go76saz2/pip-build-env-yzlgivyr/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 302, in _get_build_requires
          self.run_setup()
        File "/gpfs/scratch/pn57fo/go76saz2/go76saz2/pip-build-env-yzlgivyr/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 318, in run_setup
          exec(code, locals())
        File "<string>", line 1, in <module>
        File "/gpfs/scratch/pn57fo/go76saz2/go76saz2/pip-build-env-yzlgivyr/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 117, in setup
          return distutils.core.setup(**attrs)
        File "/gpfs/scratch/pn57fo/go76saz2/go76saz2/pip-build-env-yzlgivyr/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 157, in setup
          dist.parse_config_files()
        File "/gpfs/scratch/pn57fo/go76saz2/go76saz2/pip-build-env-yzlgivyr/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 608, in parse_config_files
          pyprojecttoml.apply_configuration(self, filename, ignore_option_errors)
        File "/gpfs/scratch/pn57fo/go76saz2/go76saz2/pip-build-env-yzlgivyr/overlay/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py", line 71, in apply_configuration
          config = read_configuration(filepath, True, ignore_option_errors, dist)
        File "/gpfs/scratch/pn57fo/go76saz2/go76saz2/pip-build-env-yzlgivyr/overlay/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py", line 139, in read_configuration
          validate(subset, filepath)
        File "/gpfs/scratch/pn57fo/go76saz2/go76saz2/pip-build-env-yzlgivyr/overlay/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py", line 60, in validate
          raise ValueError(f"{error}\n{summary}") from None
      ValueError: invalid pyproject.toml config: `project.optional-dependencies.rapids11[1]`.
      configuration error: `project.optional-dependencies.rapids11[1]` must be pep508
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

```

**i assume that the '\*' in "cuvs-cu11>=24.4.\*" under optional dependencies is causing the issue but not sure how to solve this.**

**Comment by EliHei2** [comment]
Hey @marzaidi thanks for reaching out. We're working on making the installation more convenient, for now please install segger like this:

```{bash}
git clone https://github.com/EliHei2/segger_dev
cd segger_dev
pip install .[rapids12] # for cuda12, and for cuda 11 use pip install .[rapids11]
```

let me know if the problem presists.

**Comment by marzaidi** [comment]
thank you for your response. unfortunately, it still does not work

```
> pip install .[rapids12]
Processing /dss/dsshome1/0C/go76saz2/segger_dev
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [48 lines of output]
      configuration error: `project.optional-dependencies.rapids11[1]` must be pep508
      DESCRIPTION:
          Project dependency specification according to PEP 508
      
      GIVEN VALUE:
          "cuvs-cu11>=24.4.*"
      
      OFFENDING RULE: 'format'
      
      DEFINITION:
          {
              "$id": "#/definitions/dependency",
              "title": "Dependency",
              "type": "string",
              "format": "pep508"
          }
      
      For more details about `format` see
      https://validate-pyproject.readthedocs.io/en/latest/api/validate_pyproject.formats.html
      
      Traceback (most recent call last):
        File "/dss/dsshome1/0C/go76saz2/miniconda3/envs/segger-env/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/dss/dsshome1/0C/go76saz2/miniconda3/envs/segger-env/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/dss/dsshome1/0C/go76saz2/miniconda3/envs/segger-env/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/gpfs/scratch/pn57fo/go76saz2/go76saz2/pip-build-env-64p5uasd/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 332, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
        File "/gpfs/scratch/pn57fo/go76saz2/go76saz2/pip-build-env-64p5uasd/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 302, in _get_build_requires
          self.run_setup()
        File "/gpfs/scratch/pn57fo/go76saz2/go76saz2/pip-build-env-64p5uasd/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 318, in run_setup
          exec(code, locals())
        File "<string>", line 1, in <module>
        File "/gpfs/scratch/pn57fo/go76saz2/go76saz2/pip-build-env-64p5uasd/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 117, in setup
          return distutils.core.setup(**attrs)
        File "/gpfs/scratch/pn57fo/go76saz2/go76saz2/pip-build-env-64p5uasd/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 157, in setup
          dist.parse_config_files()
        File "/gpfs/scratch/pn57fo/go76saz2/go76saz2/pip-build-env-64p5uasd/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 608, in parse_config_files
          pyprojecttoml.apply_configuration(self, filename, ignore_option_errors)
        File "/gpfs/scratch/pn57fo/go76saz2/go76saz2/pip-build-env-64p5uasd/overlay/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py", line 71, in apply_configuration
          config = read_configuration(filepath, True, ignore_option_errors, dist)
        File "/gpfs/scratch/pn57fo/go76saz2/go76saz2/pip-build-env-64p5uasd/overlay/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py", line 139, in read_configuration
          validate(subset, filepath)
        File "/gpfs/scratch/pn57fo/go76saz2/go76saz2/pip-build-env-64p5uasd/overlay/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py", line 60, in validate
          raise ValueError(f"{error}\n{summary}") from None
      ValueError: invalid pyproject.toml config: `project.optional-dependencies.rapids11[1]`.
      configuration error: `project.optional-dependencies.rapids11[1]` must be pep508
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by EliHei2** [comment]
hi @marzaidi did you fresh-cloned the repo? because this looks like the former version.

**Comment by marzaidi** [comment]
hi @EliHei2, thanks for your response. i was able to successfully install it using `pip install .[rapids12]` and also (FYI) had to use `pip install -e ".[faiss]"`
