### ISSUE TITLE
[BUG] runtime error while making predictions

### ISSUE THREAD

**Issue by marzaidi** [EliHei2/segger_dev#52]
following the tutorial on https://elihei2.github.io/segger_dev/notebooks/segger_tutorial/ and i get a runtime error at step 3:

```
# Checkpoint directory for Lightning model above
model_version = 0

# Load in latest checkpoint
model_path = models_dir / 'lightning_logs' / f'version_{model_version}'
model = load_model(model_path / 'checkpoints')
dm.setup()

receptive_field = {'k_bd': 4, 'dist_bd': 12,'k_tx': 15, 'dist_tx': 3}

# Perform segmentation (predictions)
segmentation = predict(
    model,
    dm.train_dataloader(),
    score_cut=0.33,  
    receptive_field=receptive_field,
    use_cc=False,
)
```

error:

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[39], line 12
      9 receptive_field = {'k_bd': 4, 'dist_bd': 12,'k_tx': 15, 'dist_tx': 3}
     11 # Perform segmentation (predictions)
---> 12 segmentation = predict(
     13     model,
     14     dm.train_dataloader(),
     15     score_cut=0.33,  
     16     receptive_field=receptive_field,
     17     use_cc=False,
     18 )

File [~/segger_dev/src/segger/prediction/predict.py:359](https://ood-2.ai.lrz.de/node/dgx-001.ai.lrz.de/8942/lab/tree/~/segger_dev/src/segger/prediction/predict.py#line=358), in predict(lit_segger, data_loader, score_cut, receptive_field, use_cc, knn_method)
    357 all_assignments = []
    358 # Use Dask delayed to parallelize the predict_batch execution and create assignments
--> 359 delayed_batches = [
    360     delayed(predict_batch)(lit_segger, batch, score_cut, receptive_field, use_cc, knn_method)
    361     for batch in data_loader
    362 ]
    364 for batch in data_loader:
    365     assignments = predict_batch(lit_segger, batch, score_cut, receptive_field, use_cc, knn_method)

File [~/segger_dev/src/segger/prediction/predict.py:359](https://ood-2.ai.lrz.de/node/dgx-001.ai.lrz.de/8942/lab/tree/~/segger_dev/src/segger/prediction/predict.py#line=358), in <listcomp>(.0)
    357 all_assignments = []
    358 # Use Dask delayed to parallelize the predict_batch execution and create assignments
--> 359 delayed_batches = [
    360     delayed(predict_batch)(lit_segger, batch, score_cut, receptive_field, use_cc, knn_method)
    361     for batch in data_loader
    362 ]
    364 for batch in data_loader:
    365     assignments = predict_batch(lit_segger, batch, score_cut, receptive_field, use_cc, knn_method)

File [~/miniconda3/envs/segger/lib/python3.10/site-packages/torch/utils/data/dataloader.py:630](https://ood-2.ai.lrz.de/node/dgx-001.ai.lrz.de/8942/lab/tree/~/miniconda3/envs/segger/lib/python3.10/site-packages/torch/utils/data/dataloader.py#line=629), in _BaseDataLoaderIter.__next__(self)
    627 if self._sampler_iter is None:
    628     # TODO(https://github.com/pytorch/pytorch/issues/76750)
    629     self._reset()  # type: ignore[call-arg]
--> 630 data = self._next_data()
    631 self._num_yielded += 1
    632 if self._dataset_kind == _DatasetKind.Iterable and \
    633         self._IterableDataset_len_called is not None and \
    634         self._num_yielded > self._IterableDataset_len_called:

File ~/miniconda3/envs/segger/lib/python3.10/site-packages/torch/utils/data/dataloader.py:1327, in _MultiProcessingDataLoaderIter._next_data(self)
   1324     return self._process_data(data)
   1326 assert not self._shutdown and self._tasks_outstanding > 0
-> 1327 idx, data = self._get_data()
   1328 self._tasks_outstanding -= 1
   1329 if self._dataset_kind == _DatasetKind.Iterable:
   1330     # Check for _IterableDatasetStopIteration

File [~/miniconda3/envs/segger/lib/python3.10/site-packages/torch/utils/data/dataloader.py:1293](https://ood-2.ai.lrz.de/node/dgx-001.ai.lrz.de/8942/lab/tree/~/miniconda3/envs/segger/lib/python3.10/site-packages/torch/utils/data/dataloader.py#line=1292), in _MultiProcessingDataLoaderIter._get_data(self)
   1289     # In this case, `self._data_queue` is a `queue.Queue`,. But we don't
   1290     # need to call `.task_done()` because we don't use `.join()`.
   1291 else:
   1292     while True:
-> 1293         success, data = self._try_get_data()
   1294         if success:
   1295             return data

File [~/miniconda3/envs/segger/lib/python3.10/site-packages/torch/utils/data/dataloader.py:1131](https://ood-2.ai.lrz.de/node/dgx-001.ai.lrz.de/8942/lab/tree/~/miniconda3/envs/segger/lib/python3.10/site-packages/torch/utils/data/dataloader.py#line=1130), in _MultiProcessingDataLoaderIter._try_get_data(self, timeout)
   1118 def _try_get_data(self, timeout=_utils.MP_STATUS_CHECK_INTERVAL):
   1119     # Tries to fetch data from `self._data_queue` once for a given timeout.
   1120     # This can also be used as inner loop of fetching without timeout, with
   (...)
   1128     # Returns a 2-tuple:
   1129     #   (bool: whether successfully get data, any: data if successful else None)
   1130     try:
-> 1131         data = self._data_queue.get(timeout=timeout)
   1132         return (True, data)
   1133     except Exception as e:
   1134         # At timeout and error, we manually check whether any worker has
   1135         # failed. Note that this is the only mechanism for Windows to detect
   1136         # worker failures.

File [~/miniconda3/envs/segger/lib/python3.10/multiprocessing/queues.py:122](https://ood-2.ai.lrz.de/node/dgx-001.ai.lrz.de/8942/lab/tree/~/miniconda3/envs/segger/lib/python3.10/multiprocessing/queues.py#line=121), in Queue.get(self, block, timeout)
    120         self._rlock.release()
    121 # unserialize the data after having released the lock
--> 122 return _ForkingPickler.loads(res)

File [~/miniconda3/envs/segger/lib/python3.10/site-packages/torch/multiprocessing/reductions.py:496](https://ood-2.ai.lrz.de/node/dgx-001.ai.lrz.de/8942/lab/tree/~/miniconda3/envs/segger/lib/python3.10/site-packages/torch/multiprocessing/reductions.py#line=495), in rebuild_storage_fd(cls, df, size)
    495 def rebuild_storage_fd(cls, df, size):
--> 496     fd = df.detach()
    497     try:
    498         storage = storage_from_cache(cls, fd_id(fd))

File [~/miniconda3/envs/segger/lib/python3.10/multiprocessing/resource_sharer.py:58](https://ood-2.ai.lrz.de/node/dgx-001.ai.lrz.de/8942/lab/tree/~/miniconda3/envs/segger/lib/python3.10/multiprocessing/resource_sharer.py#line=57), in DupFd.detach(self)
     56 '''Get the fd.  This should only be called once.'''
     57 with _resource_sharer.get_connection(self._id) as conn:
---> 58     return reduction.recv_handle(conn)

File [~/miniconda3/envs/segger/lib/python3.10/multiprocessing/reduction.py:189](https://ood-2.ai.lrz.de/node/dgx-001.ai.lrz.de/8942/lab/tree/~/miniconda3/envs/segger/lib/python3.10/multiprocessing/reduction.py#line=188), in recv_handle(conn)
    187 '''Receive a handle over a local connection.'''
    188 with socket.fromfd(conn.fileno(), socket.AF_UNIX, socket.SOCK_STREAM) as s:
--> 189     return recvfds(s, 1)[0]

File [~/miniconda3/envs/segger/lib/python3.10/multiprocessing/reduction.py:164](https://ood-2.ai.lrz.de/node/dgx-001.ai.lrz.de/8942/lab/tree/~/miniconda3/envs/segger/lib/python3.10/multiprocessing/reduction.py#line=163), in recvfds(sock, size)
    162     sock.send(b'A')
    163 if len(ancdata) != 1:
--> 164     raise RuntimeError('received %d items of ancdata' %
    165                        len(ancdata))
    166 cmsg_level, cmsg_type, cmsg_data = ancdata[0]
    167 if (cmsg_level == socket.SOL_SOCKET and
    168     cmsg_type == socket.SCM_RIGHTS):

RuntimeError: received 0 items of ancdata
```

i tried to adjust system limits (`ulimit -n`) and disabled multiprocessing in pytorch (`num_workers=0`) but nothing worked, thanks in advance!

**Comment by quail768** [comment]
@EliHei2 issue is back in the version I cloned today. Sorry😅
```
Traceback (most recent call last):
  File "/Segger/Predictions.py", line 43, in <module>
    segmentation = predict(
  File "/segger_dev/src/segger/prediction/predict.py", line 359, in predict
    delayed_batches = [
  File "/segger_dev/src/segger/prediction/predict.py", line 359, in <listcomp>
    delayed_batches = [
  File "/omics/odcf/analysis/OE0211_projects/ndmm/Aaron/CondaEnvironments/MuSiCal/segger/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/segger/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1327, in _next_data
    idx, data = self._get_data()
  File "/segger/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1293, in _get_data
    success, data = self._try_get_data()
  File "/segger/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1131, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/segger/lib/python3.10/multiprocessing/queues.py", line 122, in get
    return _ForkingPickler.loads(res)
  File "/segger/lib/python3.10/site-packages/torch/multiprocessing/reductions.py", line 496, in rebuild_storage_fd
    fd = df.detach()
  File "/segger/lib/python3.10/multiprocessing/resource_sharer.py", line 58, in detach
    return reduction.recv_handle(conn)
  File "/segger/lib/python3.10/multiprocessing/reduction.py", line 189, in recv_handle
    return recvfds(s, 1)[0]
  File "/segger/lib/python3.10/multiprocessing/reduction.py", line 164, in recvfds
    raise RuntimeError('received %d items of ancdata' %
RuntimeError: received 0 items of ancdata



```

**Comment by EliHei2** [comment]
could you please provide the full script? are you using dataloader with num_workers > 0?

**Comment by quail768** [comment]
```
from segger.data.io import XeniumSample
from segger.training.train import LitSegger
from segger.training.segger_data_module import SeggerDataModule
from segger.prediction.predict import predict, load_model, segment
from lightning.pytorch.loggers import CSVLogger
from pytorch_lightning import Trainer
from pathlib import Path
from lightning.pytorch.plugins.environments import LightningEnvironment
from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
import matplotlib.pyplot as plt

# Paths to Xenium sample data and where to store Segger data
xenium_data_dir = Path('/mnt/N5_T2/Xenium_Exp')
segger_data_dir = Path('/mnt/N5_T2/segger/')

# Setup Xenium sample to create dataset
xs = XeniumSample(verbose=False)
xs.set_file_paths(
    transcripts_path=xenium_data_dir / 'transcripts.parquet',
    boundaries_path=xenium_data_dir / 'nucleus_boundaries.parquet',
)
xs.set_metadata()

models_dir = Path('/mnt/models')
# Checkpoint directory for Lightning model above
model_version = 5

# Load in latest checkpoint
model_path = models_dir / 'lightning_logs' / f'version_{model_version}'
model = load_model(model_path / 'checkpoints')
dm = SeggerDataModule(
    data_dir=segger_data_dir,
    batch_size=2,  
    num_workers=6,  
)
dm.setup()
save_directory=Path('/mnt/N5_T2/segout')
segmentation_tag = 'N5_T2'  
transcript_file_path = Path('/mnt/N5_T2/Xenium_Exp/transcripts.parquet')  
score_cutoff = 0.5  
# Optional parameters
file_format = 'anndata'  
use_connected_components = False 
knn_algorithm = 'kd_tree' 
verbose_output = True  

# Receptive field configuration
receptive_field_config = {'k_bd': 4, 'dist_bd': 12, 'k_tx': 15, 'dist_tx': 3}

# Call the `segment` function
segment(
    model=model, 
    dm=dm, 
    save_dir=save_directory, 
    seg_tag=segmentation_tag, 
    transcript_file=transcript_file_path, 
    score_cut=score_cutoff, 
    use_cc=use_connected_components, 
    file_format=file_format, 
    receptive_field=receptive_field_config, 
    knn_method=knn_algorithm, 
    verbose=verbose_output
)


```

I cloned a version yesterday and that worked with dataloader with num_workers > 0. Not sure if that's relevant but letting you know.

**Comment by EliHei2** [comment]
yes unfortunately we don't support `num_workers >0` for the data module for prediction currently, you can set it to 0, and it should be fine.

```
dm = SeggerDataModule(
    data_dir=segger_data_dir,
    batch_size=2,  
    num_workers=0,  
)
```

pining @daniel-unyi-42  for 1) adding to the docs and 2) fixing the issue.

**Comment by quail768** [comment]
Just ran this

```
from segger.data.io import XeniumSample
from segger.training.train import LitSegger
from segger.training.segger_data_module import SeggerDataModule
from segger.prediction.predict import predict, load_model, segment
from lightning.pytorch.loggers import CSVLogger
from pytorch_lightning import Trainer
from pathlib import Path
from lightning.pytorch.plugins.environments import LightningEnvironment
from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
import matplotlib.pyplot as plt

# Paths to Xenium sample data and where to store Segger data
xenium_data_dir = Path('/mnt/N5_T2/Xenium_Exp')
segger_data_dir = Path('/mnt/N5_T2/segger/')

# Setup Xenium sample to create dataset
xs = XeniumSample(verbose=False)
xs.set_file_paths(
    transcripts_path=xenium_data_dir / 'transcripts.parquet',
    boundaries_path=xenium_data_dir / 'nucleus_boundaries.parquet',
)
xs.set_metadata()

models_dir = Path('/mnt/models')
# Checkpoint directory for Lightning model above
model_version = 5

# Load in latest checkpoint
model_path = models_dir / 'lightning_logs' / f'version_{model_version}'
model = load_model(model_path / 'checkpoints')
dm = SeggerDataModule(
    data_dir=segger_data_dir,
    batch_size=2,  
    num_workers=0,  
)
dm.setup()
save_directory=Path('/mnt/N5_T2/segout')
segmentation_tag = 'N5_T2'  
transcript_file_path = Path('/mnt/N5_T2/Xenium_Exp/transcripts.parquet')  
score_cutoff = 0.5  
# Optional parameters
file_format = 'anndata'  
use_connected_components = False 
knn_algorithm = 'kd_tree' 
verbose_output = True  

# Receptive field configuration
receptive_field_config = {'k_bd': 4, 'dist_bd': 12, 'k_tx': 15, 'dist_tx': 3}

# Call the `segment` function
segment(
    model=model, 
    dm=dm, 
    save_dir=save_directory, 
    seg_tag=segmentation_tag, 
    transcript_file=transcript_file_path, 
    score_cut=score_cutoff, 
    use_cc=use_connected_components, 
    file_format=file_format, 
    receptive_field=receptive_field_config, 
    knn_method=knn_algorithm, 
    verbose=verbose_output
)

```
Same error
